default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DB_NAME") { "sellio" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASS") { "test" } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

production:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "postgres" } %>
