default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: sellio
  username: postgres
  password: test
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sellio_test
  username: postgres
  password: test
  host: localhost
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: postgres
  password: <%= ENV['DB_PASS'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
